inventree_object.py
=> API improvements

inventree_api.py
- User can supply token directly when constructing the API
- Or token can be retrieved based on supplied username/password
- Token requests provide at least 10x speed improvement
Ref: https://github.com/inventree/InvenTree/pull/407
=> Enable token-based authentication

inventree_api.py
Matching PR for https://github.com/inventree/InvenTree/pull/735
=> Fix for token auth

inventree_object.py
Should now pass all flake8 checks
=> formatting: indents, whitespace

inventree/api.py, inventree/base.py, setup.py
Fixes https://github.com/inventree/inventree-python/issues/17
=> Error info

inventree/api.py, inventree/base.py, scripts/test_server_connection.py, setup.py
Add a test script to check connection to an InvenTree server
=> Test script

inventree/base.py, inventree/build.py, inventree/company.py, inventree/order.py, inventree/part.py, inventree/stock.py
I tested it with my application. I hope it matches the intention of https://github.com/inventree/inventree-python/issues/22
=> Removed FILTERS and FILTERS_EXTRA from all classes and from InventreeObject.list() method

inventree/api.py
Makes my test output cleaner :smile:
=> Replaced api delete confirmation print with logging.debug

inventree/base.py
(cherry picked from commit 79adb79016d423d5a64c2603ab01592a5575b1b0)
=> Bump version number

.gitignore, inventree/part.py, inventree/stock.py, setup.cfg, test/test_api.py, test/test_data.json
Adds some more convenience functions for the Python API
Fixes https://github.com/inventree/inventree-python/issues/45
=> Add API features

inventree/api.py
Fixes https://github.com/inventree/inventree-python/issues/48
=> Raise exception if cannot connect to server

inventree/company.py, test/test_api.py
=> Added manufacturer part API object

inventree/api.py, inventree/base.py, inventree/company.py, inventree/order.py, setup.cfg, test/test_api.py, test/test_company.py, test/test_order.py, test/test_part.py
Ref: https://github.com/inventree/InvenTree/pull/1707
=> Increase code coverage for unit testing

.gitignore, inventree/api.py, inventree/base.py, inventree/part.py, test/test_api.py, test/test_company.py, test/test_part.py
- Remove PartThumb class
- Adds ability to PATCH
- Adds ability to add files to PATCH and PUT and POST requests
=> Refactor uploadImage function for part

test/test_part.py
Changes required from https://github.com/inventree/InvenTree/pull/1700
=> Deactivate part before deleting

inventree/api.py, inventree/base.py, inventree/company.py, inventree/part.py, test/test_api.py, test/test_part.py
Closes https://github.com/inventree/inventree-python/issues/72
=> Adds API function for downloading file

inventree/part.py, test/test_internal_price.py, test/test_part.py
Saw there was an abandoned PR for this (#64 ), wanted this feature for an app I'm working on
=> Add Interface for InternalPrice Model

inventree/base.py, inventree/part.py
Needed this for my import program.
=> added code for getting and deleting relationships

inventree/api.py, test/test_api.py, test/test_part.py
Closes https://github.com/inventree/inventree-python/issues/93
=> Raise errors when returning invalid status code from the server

inventree/company.py, test/test_company.py
Closes https://github.com/inventree/inventree-python/issues/99
=> Manufacturer part attachment

inventree/base.py, setup.py
Ref: https://github.com/inventree/inventree-python/issues/110
=> Set minimum version for requests package

inventree/order.py
I think I put that there, I'm sorry about that :) Shouldn't be there, though
=> Remove extra slash

.github/workflows/ci.yaml, requirements.txt, test/test_order.py
Updating unit tests to match new reference fields format.
Ref: https://github.com/inventree/InvenTree/pull/3267
=> Update unit tests

test/test_part.py
Ref: https://github.com/inventree/inventree-python/pull/116
=> Add unit test for pagination

inventree/api.py, inventree/base.py, inventree/order.py, inventree/part.py, inventree/stock.py, test/test_part.py
Closes https://github.com/inventree/inventree-python/issues/98
- Adds support for "metadata" attributes for multiple models
- Ref: https://github.com/inventree/InvenTree/pull/2957
=> Model metadata support

inventree/api.py, test/test_api.py, test/test_company.py, test/test_order.py, test/test_part.py
This PR provides a number of core improvements, most notably fixing an issue which prevented complex json data from being sent as payload for a POST request.
Ref: https://github.com/inventree/inventree-python/pull/115
=> Fixes bugs in POST request

inventree/stock.py, test/test_stock.py
Closes https://github.com/inventree/inventree-python/issues/81
=> Stock adjustment actions

inventree/base.py
Update version number for `0.8.0`
=> Update version number

test/test_order.py
Ref: https://github.com/inventree/InvenTree/pull/3615
=> Accept incomplete lines in PO complete unit test

.github/workflows/ci.yaml, inventree/base.py, inventree/order.py, inventree/part.py, tasks.py, test/docker-compose.yml, test/test_order.py, test/test_stock.py
After some recent updates to the inventree core codebase, the unit tests for these python bindings started to fail.
In the process of fixing the unit tests I've also found and addresses some actual bugs.
=> Unit test fixes

inventree/label.py, inventree/part.py, inventree/stock.py, test/test_label.py
This adds basic functionality for Label (Part, StockItem, StockLocation) such as listing, as well as a 'printlabel' function to the relevant classes.
This function can either use a plugin, or save the created label to a file.
No tests implemented yet, therefore this is a draft.
This PR should fix #44.
=> Add Label objects and printing method

test/test_stock.py
Ref: https://github.com/inventree/InvenTree/pull/3889
=> Fix unit tests

inventree/base.py, test/test_part.py
Allows quick method of counting the number of results for a given query
=> Adds "count" functionality for each API endpoint

inventree/stock.py, test/test_stock.py
Use `/api/stock/assign/` endpoint.
Relies on existing functions as much as possible.
=> Add functions for assigning stock items to a customer

inventree/user.py
Just a small addition to get access to the user list.
=> Add class for listing users

inventree/base.py
See #158 for details.
This should correct usage.
Let's see what the tests result in..
=> Fix usage of kwargs (Fix #158)

inventree/base.py, inventree/currency.py, test/test_currency.py
This PR adds support for the new "exchange rate" API endpoints.
Ref: https://github.com/inventree/inventree-python/issues/163
Ref: https://github.com/inventree/InvenTree/pull/4300
Ref: https://github.com/inventree/InvenTree/pull/4293
Adds manager class for requesting currency information from the InvenTree server.
=> Currency support

inventree/api.py, requirements.txt
Added proxy support to all requests. I did not bother adding unit tests for this feature as I think this feature is to user setup specific to catch it with unit tests. I did run the existing unit test to see if it breaks something without using proxies (it did not) and tested the proxy features manually.
Closes #168
=> Add proxy support

inventree/part.py, test/test_part.py
Add getRequirements() method, to give information contained in 'requirements' API endpoint
=> Add function for Part requirements

inventree/api.py
Closes https://github.com/inventree/inventree-python/issues/171
=> Remove code which hard-coded "connected" to True

test/test_part.py
Ref: https://github.com/inventree/InvenTree/pull/4571
=> Remove "problematic" unit test

inventree/api.py, test/test_api.py
This implements #180.
It also adjust requestToken() to catch exceptions in cases the server is not connected.
=> Auth check

inventree/project_code.py, test/test_project_codes.py
Closes https://github.com/inventree/inventree-python/issues/184
=> Project code support

inventree/build.py, inventree/company.py, inventree/label.py, inventree/part.py, inventree/purchase_order.py, inventree/sales_order.py, inventree/stock.py
See https://github.com/inventree/inventree-python/issues/188
=> Add Metadata

inventree/label.py, test/test_project_codes.py
Ref: https://github.com/inventree/InvenTree/pull/5251
Support for the new plugin-based approach to label printing. With this update, both the "new" and "old" methods should be supported natively.
=> Support updated label printing

inventree/label.py, inventree/part.py, inventree/stock.py
=> rename LabelPrintingMixing to LabelPrintingMixin #204

inventree/api.py, test/test_stock.py
Ref: https://github.com/inventree/InvenTree/pull/5937
=> Stringify barcode data before scanning

inventree/api.py, inventree/base.py, inventree/currency.py, inventree/label.py, inventree/purchase_order.py, inventree/sales_order.py, inventree/stock.py, test/docker-compose.yml, test/test_label.py, test/test_stock.py
Adjust unit testing so that it passes for `0.12.x` InvenTree branch
=> Fix label printing for older server version

.pre-commit-config.yaml, ci/check_version_number.py, inventree/api.py, inventree/base.py, inventree/build.py, inventree/company.py, inventree/currency.py, inventree/label.py, inventree/order.py, inventree/part.py, inventree/project_code.py, inventree/purchase_order.py, inventree/return_order.py, inventree/sales_order.py, inventree/stock.py, inventree/user.py, tasks.py, test/test_api.py, test/test_base.py, test/test_build.py, test/test_company.py, test/test_currency.py, test/test_internal_price.py, test/test_label.py, test/test_order.py, test/test_part.py, test/test_project_codes.py, test/test_stock.py
This is based on the one from the main InvenTree repository, but simplified.
Flake8 has been simplified, since it caused lots of errors before.
=> Add a pre-commit configuration

inventree/build.py, inventree/part.py, inventree/purchase_order.py, inventree/report.py, inventree/return_order.py, inventree/sales_order.py, inventree/stock.py, test/test_report.py
This is along the lines of the LabelPrinting mixin and Label classes
=> Add Report support: Classes for Report objects, and printing mixin

inventree/api.py, inventree/label.py, inventree/report.py, test/dummytemplate.html, test/dummytemplate2.html, test/test_label.py, test/test_report.py
This adds convenience functions which make it easier to use the API to create and update labels and reports using local files. It allows downloading template files from the server, which can be a good starting point.
If you agree with adding these functions I can add some tests.
=> Add functions to easily download template files, create new labels/reports, and update settings

inventree/company.py
Support for company.address model type
=> Add support for Address model

inventree/part.py, inventree/stock.py
Ref: https://github.com/inventree/InvenTree/pull/6430
Accommodate new API changes related to PartTestTemplate and StockItemTestResult objects
=> Test result templates

test/test_part.py
- Once https://github.com/inventree/InvenTree/pull/6767 is merged
=> Fix unit test

inventree/part.py
Hi,
I needed the SalePrice in the part class, so I added it because it was not available.
Greetings,
Lars
=> add SalePrice to the part class

inventree/base.py, inventree/label.py, inventree/plugin.py, inventree/report.py, test/test_plugin.py
- Update API for PluginConfig model
- Uses 'key' as the PK, no 'pk'
- Ref: https://github.com/inventree/InvenTree/pull/7224
=> Update plugin API

inventree/base.py, inventree/build.py, inventree/purchase_order.py, inventree/return_order.py, inventree/sales_order.py, test/test_build.py
- Ref: https://github.com/inventree/InvenTree/pull/7807
- Adds "order hold" functionality
- Update unit tests
=> Order Hold

.github/workflows/ci.yaml, inventree/api.py, inventree/base.py
- https://github.com/inventree/InvenTree/discussions/8101
- https://github.com/inventree/inventree-python/issues/233
=> Adds option to bypass strict HTTPS checks

inventree/purchase_order.py
Add `expiry_date` arg to the `PurchaseOrderLineItem.receive()` function.
Depends on https://github.com/inventree/InvenTree/pull/8867 being accepted
=> Add expiry date to po line item receive

test/test_company.py
- Remove 'unit' field check
- Ref: https://github.com/inventree/InvenTree/pull/9150
=> Update unit testing

inventree/base.py, setup.py
- Fix SSL issues on Windows
- Bump min python version to 3.9
=> Add new package requirement

test/test_api.py
- Ensure that the test keys match existing templates
- Ref: https://github.com/inventree/InvenTree/pull/10146
=> Tweak unit tests
