inventree/inventree-python

inventree/base.py, inventree/part.py
The URL was incorrect, it was missing the category PK.
Also the CategoryParameterTemplate class was useless.
=> Fix for fetching category parameters

inventree/api.py, inventree/base.py, inventree/part.py, inventree/stock.py
This PR fixes the problem discussed in #87 which created exceptions when using the logging module with rotating file handlers. For this, all format string statements that previously missed their format placeholders as well as general logging statements that require formating were replaced with f-strings. 
Some other stray format statements were also replaced in #a3cd5da to be consistent with string formating.
=> Update syntax of logging statements (to fix #87)

inventree/api.py
The timeout is easily reached when running `company.getSuppliedParts()` with a company having 300+ supplied parts.
=> Increase server request timeout to 10s

inventree/order.py, test/test_order.py
I have copied the relevant functions for PO Line items so that they work for extra line items as well.
These were previously missing from the python API
=> Add PO ExtraLineItems functionality to API

test/test_part.py
Adds a few tests for Parameter and ParameterTemplate classes.
While making these tests, I realised that there is no ParameterTemplate.delete() support by the API.
=> Add tests for Part Parameters and ParameterTemplates

test/test_part.py
This was missing in PR #107 because the ParameterTemplate delete functionality was not implemented in the back end.
Now that it is (see [this PR](https://github.com/inventree/InvenTree/pull/3123)), this can be added again.
=> Test for deleting parametertemplates

inventree/order.py, test/test_order.py
The Sales Order classes were missing the ExtraLineItems functions; these have been copied from PurchaseOrder templates.
Tests for adding and deleting a sales order extra line item added
=> Add ExtraLine functions for Sales Order

inventree/base.py
When adding the limit= parameter to list it causes InvenTree to modify the output of the rest response to be a dict instead of a simple array of results. Inside of that dict includes a results array that inventree-python is actually looking for. Without this addition inventree-python will ignore the result and return an empty result set.
=> Add support for simple parsing of paginated response

inventree/base.py, inventree/company.py, inventree/stock.py, test/test_build.py, test/test_stock.py
Closes https://github.com/inventree/inventree-python/issues/129
Adds a mixin class which provides support for bulk deletion in a single API call
- Only for models which support this feature on the backend
- Requires API version 58
=> Add support for bulk delete operations

inventree/part.py, test/test_part.py
Adds (or fixes) support for PartCategoryParameterTemplate class
Fixes https://github.com/inventree/inventree-python/issues/131
Note that the method `get_category_parameter_templates` has been renamed to `getCategoryParameterTemplates`
=> Category template fix

tasks.py
I often have problems that the test server does not come up after a series of tests.
This change, which makes the docker containers go down before resetting the data in them, seems to solve these issues. I also added a note in the docstring about the --reset flag (to clarify behaviour).
=> Stop server when resetting during tests

inventree/api.py, inventree/label.py
The label printing did format the url parameters directly into the string. While this works fine for the download case, the normal api calls will force a trailing slash breaking this.
The patch fixed it, by passing the parameters as an explicit params dictionary.
=> Fix label printing

inventree/part.py, test/test_part.py
These tests cover functions not yet tested according to [Coveralls](https://coveralls.io/builds/54390705/source?filename=inventree%2Fpart.py)
While making tests, I realised that functions getunits() and getSupplierParts() for non-purchaseable parts needed modification.
Goal is to get 100% test coverage for the part.py file
=> Add tests for Part functions

inventree/order.py, test/test_order.py
This adds two methods, and tests, as described in #82 
For receiving a single line item of a PO:
`PurchaseOrderLineItem.receive(...`
with the ability to give details (quantity, status, batch codes, serial numbers, etc)
`PurchaseOrder.receiveAll(...`
The quick method, which can be run given only a location (limitation of the API, not the python binding), and sets all line items as received.
=> Receive line items (Fix #82)

inventree/api.py, inventree/base.py, test/test_api.py
Sometimes my server is a bit slow in replying. I would like to be able to set a more lenient timeout parameter in requests.
@SchrodingersGat: Is there a specific reason the timeout is 2.5s in the testServer function? I've set the default timeout to the 10s found elsewhere as the current standard, and it's the same everywhere - unless overwritten in a specific request (as before).
=> Inventree python timeout

inventree/base.py
Without these, calling code such as the following on `R` being any InventreeObject, will fail:
```
dict(R)
'pk' in R
R.keys()
```
with an error something like this:
```
File "... inventree-python/inventree/base.py", line 310, in __getitem__
raise KeyError(f"Key '{name}' does not exist in dataset")
KeyError: "Key '0' does not exist in dataset"
```
After adding these methods, the above results in something like this:
```
>>> dict(R)
{'pk': 12, 'name': 'Dimension', 'units': '', 'description': ''}
>>> R.keys()
dict_keys(['pk', 'name', 'units', 'description'])
>>> 'pk' in R
True
```
=> Add keys(), __contains__ method to InventreeObject

inventree/stock.py
Without this, searching for a specific test key, eg `getTestResults(test='timeto70c')` does not filter results.
=> Add missing kwargs to call of list function, to allow searching

TESTING.md, inventree/base.py, inventree/build.py, inventree/company.py, inventree/part.py, inventree/purchase_order.py, inventree/return_order.py, inventree/sales_order.py, inventree/stock.py, test/test_part.py
This adds an `add_link` class method to the `Attachment` class, to make it possible to add external link attachments via the python api.
Should I also add a bunch of `addLinkAttachment` functions to `Part`, `Company`, etc. (similar to the `uploadAttachment` methods)?
=> Add add_link function to Attachment class

inventree/api.py
- Allows better token control on the server
=> Specify token name when requesting token

inventree/part.py, inventree/stock.py
From StockItemTestResult, go via PartTestTemplate. Try to use defined key first.
(Previously, getting 'self.test' in StockItemTestResult would fail)
=> Fix getting test key

inventree/base.py, inventree/build.py, inventree/company.py, inventree/label.py, inventree/part.py, inventree/plugin.py, inventree/project_code.py, inventree/purchase_order.py, inventree/report.py, inventree/return_order.py, inventree/sales_order.py, inventree/stock.py, tasks.py, test/test_label.py, test/test_plugin.py, test/test_report.py
Working on a new implementation of label and report printing, to match the updated API version:
Ref: https://github.com/inventree/InvenTree/pull/7074
The intent here is that both "modern" and "legacy" API versions will be supported concurrently, at least until we decide to deprecate the "old" API in the future.
=> New printing api

inventree/api.py, inventree/base.py, inventree/build.py, inventree/company.py, inventree/currency.py, inventree/label.py, inventree/order.py, inventree/part.py, inventree/purchase_order.py, inventree/report.py, inventree/return_order.py, inventree/sales_order.py, inventree/stock.py, tasks.py, test/docker-compose.yml, test/test_build.py, test/test_company.py, test/test_label.py, test/test_order.py, test/test_part.py, test/test_report.py, test/test_stock.py
- Support legacy API
- Support modern API
- Ref: https://github.com/inventree/InvenTree/pull/7420
=> Refactor attachment class

inventree/base.py, inventree/sales_order.py, tasks.py, test/test_order.py
Adds support for the SalesOrderAllocation model
Additionally fixes some bugs with the SalesOrderShipment model.
Note: Requires https://github.com/inventree/InvenTree/pull/8250 to be merged!
=> Sales Order Allocation

inventree/base.py, test/test_order.py
- Closes https://github.com/inventree/inventree-python/issues/246
- Handles an error thrown during a `list()` call, and returns an empty list
=> Fix for list which raises an error

inventree/sales_order.py
This commit:
- adds MIN_API_VERSION to SalesOrderAllocation model
- adds a workaround for older versions of InvenTree server, allowing use of the old `allocations` data.
See https://github.com/inventree/inventree-python/issues/250 for explanation.
=> Improve compatibility with older versionof InvenTree Server.

inventree/purchase_order.py
- Fix default value for "expiry_date"
=> Fix for PurchaseOrderLineItem.receive

inventree/api.py, inventree/base.py
- Pass 'verify=<x>' to all API calls
- Closes https://github.com/inventree/inventree-python/issues/260
=> Fix for https verification

inventree/part.py
The `BomItemSubstitute` database model was missing in the python API. This PR adds it.
=> Add BomItemSubstitute

inventree/stock.py, test/test_api.py, test/test_stock.py
Since inventree/InvenTree#9857 the `StockItem` create API has been able to return multiple items for a single call. The python API was not updated to handle this (as tested by the first commit on this branch), which blocked my attempt at fixing the annotations to generate a usable API schema (inventree/InvenTree#9969).
Breaking: This PR changes `StockItem` create to always return a list of items.
With these changes both `master` and inventree/InvenTree#9969 are able to pass the API tests.
As always, let me know if anything needs to change to fit Python conventions/project style/etc.
=> Handle list returns from creating StockItems

test/test_order.py
Ref: https://github.com/inventree/InvenTree/pull/10174
=> Tweak unit tests

README.md, pyproject.toml
fixes #274 
Make `pip-system-certs` an optional dependency, allowing the user to tune the install to fit their environment
=> Make pip-system-certs an optional extra
